{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 4,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NEW_LEAF",
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "CURSED_PEARL",
                "title": {
                  "key": "CURSED_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MURDER"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 106,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.CORROSIVE_WAVE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              },
              {
                "final_card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.LEADING_STRIKE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFEND_SILENT"
                }
              }
            ],
            "current_gold": 6,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MORPHIC_GROVE.pages.INITIAL.options.GROUP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 100,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.MORPHIC_GROVE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SOWN"
                  },
                  "floor_added_to_deck": 3,
                  "id": "CARD.CORROSIVE_WAVE"
                },
                "enchantment": "ENCHANTMENT.SOWN"
              }
            ],
            "current_gold": 6,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SAPPHIRE_SEED.pages.INITIAL.options.PLANT.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sown"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SAPPHIRE_SEED",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEG_SWEEP"
              }
            ],
            "current_gold": 13,
            "current_hp": 55,
            "damage_taken": 1,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 13,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PREPARED"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPEEDSTER"
              }
            ],
            "current_gold": 46,
            "current_hp": 17,
            "damage_taken": 38,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 46,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NOXIOUS_FUMES"
              }
            ],
            "current_gold": 72,
            "current_hp": 20,
            "damage_taken": 18,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE"
            ],
            "room_type": "elite",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 103,
            "current_hp": 20,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.MOLTEN_EGG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 111,
            "current_hp": 20,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 143,
            "current_hp": 19,
            "damage_taken": 1,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BEETLE_JUICE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SWIFT_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYRDONIS_ELITE",
            "monster_ids": [
              "MONSTER.BYRDONIS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHOCKWAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SECRET_TECHNIQUE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 20,
            "current_hp": 19,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 123,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": false
              },
              {
                "choice": "POTION.CURE_ALL",
                "was_picked": false
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOOK_OF_FIVE_RINGS",
                "was_picked": false
              },
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": false
              },
              {
                "choice": "RELIC.LAVA_LAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 20,
            "current_hp": 8,
            "damage_taken": 11,
            "event_choices": [
              {
                "title": {
                  "key": "DENSE_VEGETATION.pages.INITIAL.options.TRUDGE_ON.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.DENSE_VEGETATION",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 35,
            "current_hp": 8,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VINE_SHAMBLER_NORMAL",
            "monster_ids": [
              "MONSTER.VINE_SHAMBLER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 35,
            "current_hp": 29,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.TOOLS_OF_THE_TRADE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STORM_OF_STEEL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TOOLS_OF_THE_TRADE"
              }
            ],
            "current_gold": 110,
            "current_hp": 17,
            "damage_taken": 12,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.ATTACK_POTION",
              "POTION.BEETLE_JUICE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CEREMONIAL_BEAST_BOSS",
            "monster_ids": [
              "MONSTER.CEREMONIAL_BEAST"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "BIIIG_HUG",
                "title": {
                  "key": "BIIIG_HUG.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TOY_BOX",
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 110,
            "current_hp": 59,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 42,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TOY_BOX",
                "was_picked": true
              },
              {
                "choice": "RELIC.PARRYING_SHIELD",
                "was_picked": true
              },
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": true
              },
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": true
              },
              {
                "choice": "RELIC.TWISTED_FUNNEL",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.STRIKE_SILENT",
              "CARD.LEADING_STRIKE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.REFLEX"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.LEG_SWEEP"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.REFLEX"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.LEG_SWEEP"
              }
            ],
            "current_gold": 120,
            "current_hp": 44,
            "damage_taken": 15,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLUR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 127,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DASH"
                },
                "was_picked": false
              }
            ],
            "current_gold": 134,
            "current_hp": 33,
            "damage_taken": 11,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "current_gold": 146,
            "current_hp": 10,
            "damage_taken": 23,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MYTES_NORMAL",
            "monster_ids": [
              "MONSTER.MYTE",
              "MONSTER.MYTE"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 146,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 24,
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.UNTOUCHABLE"
              }
            ],
            "current_gold": 159,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 25,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 174,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_SILK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 213,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.MEAL_TICKET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.UNTOUCHABLE"
              },
              {
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 213,
            "current_hp": 31,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 213,
            "current_hp": 31,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ACROBATICS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FOLLOW_THROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GRAND_FINALE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACK_OF_ALL_TRADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THE_GAMBIT"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 113,
            "current_hp": 46,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": false
              },
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": false
              },
              {
                "choice": "RELIC.ROYAL_STAMP",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 30,
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HAND_TRICK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.REFLEX"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TACTICIAN"
              }
            ],
            "current_gold": 125,
            "current_hp": 44,
            "damage_taken": 2,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CLARITY",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LOUSE_PROGENITOR_NORMAL",
            "monster_ids": [
              "MONSTER.LOUSE_PROGENITOR"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 156,
            "current_hp": 42,
            "damage_taken": 2,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 156,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.CORROSIVE_WAVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_OF_INK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CORROSIVE_WAVE"
              }
            ],
            "current_gold": 231,
            "current_hp": 49,
            "damage_taken": 14,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FYSH_OIL"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
            "monster_ids": [
              "MONSTER.KNOWLEDGE_DEMON"
            ],
            "room_type": "boss",
            "turns_taken": 6
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LOOMING_FRUIT",
                "title": {
                  "key": "LOOMING_FRUIT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "FUR_COAT",
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SIGNET_RING",
                "title": {
                  "key": "SIGNET_RING.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 1230,
            "current_hp": 65,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SIGNET_RING.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 999,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 16,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SIGNET_RING",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 35,
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SPEEDSTER"
              }
            ],
            "current_gold": 1240,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "current_gold": 1254,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.CLARITY"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 1254,
            "current_hp": 65,
            "damage_taken": 0,
            "downgraded_cards": [
              "CARD.PREPARED",
              "CARD.STRIKE_SILENT"
            ],
            "event_choices": [
              {
                "title": {
                  "key": "REFLECTIONS.pages.INITIAL.options.TOUCH_A_MIRROR.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "upgraded_cards": [
              "CARD.PREPARED",
              "CARD.NEUTRALIZE",
              "CARD.LEG_SWEEP",
              "CARD.DEFEND_SILENT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.REFLECTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 1254,
            "current_hp": 23,
            "damage_taken": 42,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_1.options.HOLD_ON_2.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_2.options.HOLD_ON_3.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_3.options.HOLD_ON_4.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_4.options.HOLD_ON_5.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_5.options.HOLD_ON_6.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Strike"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.PURITY"
            ],
            "bought_potions": [
              "POTION.FORTIFIER"
            ],
            "bought_relics": [
              "RELIC.CENTENNIAL_PUZZLE",
              "RELIC.SCREAMING_FLAGON",
              "RELIC.MERCURY_HOURGLASS"
            ],
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ENTROPY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              },
              {
                "id": "CARD.PURITY"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              }
            ],
            "current_gold": 261,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 993,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": true
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              },
              {
                "choice": "RELIC.SCREAMING_FLAGON",
                "was_picked": true
              },
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 261,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 296,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 42,
                  "id": "CARD.HAND_TRICK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLUR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.HAND_TRICK"
              }
            ],
            "current_gold": 326,
            "current_hp": 46,
            "damage_taken": 13,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TINGSHA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MIND_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SALVO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ESCAPE_PLAN"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_SILENT"
              }
            ],
            "current_gold": 140,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 186,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": false
              },
              {
                "choice": "RELIC.SLING_OF_COURAGE",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 44,
                  "id": "CARD.TRACKING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TRACKING"
              }
            ],
            "current_gold": 168,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "current_gold": 177,
            "current_hp": 56,
            "damage_taken": 5,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CLARITY",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.VULNERABLE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GLOBE_HEAD_NORMAL",
            "monster_ids": [
              "MONSTER.GLOBE_HEAD"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNIFE_TRAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FOLLOW_THROUGH"
                },
                "was_picked": false
              }
            ],
            "current_gold": 210,
            "current_hp": 54,
            "damage_taken": 2,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 210,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PREPARED"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 210,
            "current_hp": 26,
            "damage_taken": 28,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.CLARITY"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DOORMAKER_BOSS",
            "monster_ids": [
              "MONSTER.DOOR"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.MURDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.PREPARED"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SOWN"
          },
          "floor_added_to_deck": 3,
          "id": "CARD.CORROSIVE_WAVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.SPEEDSTER"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.ACROBATICS"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.TOOLS_OF_THE_TRADE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.LEG_SWEEP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.REFLEX"
        },
        {
          "floor_added_to_deck": 24,
          "id": "CARD.UNTOUCHABLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 25,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.UNTOUCHABLE"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 30,
          "id": "CARD.TACTICIAN"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.CORROSIVE_WAVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.SPEEDSTER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.PURITY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 42,
          "id": "CARD.HAND_TRICK"
        },
        {
          "floor_added_to_deck": 43,
          "id": "CARD.ESCAPE_PLAN"
        },
        {
          "floor_added_to_deck": 44,
          "id": "CARD.TRACKING"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.FORTIFIER",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.VAMBRACE"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.MOLTEN_EGG"
        },
        {
          "floor_added_to_deck": 12,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.TOY_BOX",
          "props": {
            "ints": [
              {
                "name": "CombatsSeen",
                "value": 16
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.PARRYING_SHIELD",
          "props": {
            "bools": [
              {
                "name": "IsMelted",
                "value": true
              },
              {
                "name": "IsWax",
                "value": true
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.WHETSTONE",
          "props": {
            "bools": [
              {
                "name": "IsMelted",
                "value": true
              },
              {
                "name": "IsWax",
                "value": true
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.ORNAMENTAL_FAN",
          "props": {
            "bools": [
              {
                "name": "IsMelted",
                "value": true
              },
              {
                "name": "IsWax",
                "value": true
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.TWISTED_FUNNEL",
          "props": {
            "bools": [
              {
                "name": "IsMelted",
                "value": true
              },
              {
                "name": "IsWax",
                "value": true
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.MEAL_TICKET"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.PETRIFIED_TOAD"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.SIGNET_RING"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.SCREAMING_FLAGON"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.TINGSHA"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.FESTIVE_POPPER"
        },
        {
          "floor_added_to_deck": 46,
          "id": "RELIC.PENDULUM"
        }
      ]
    }
  ],
  "run_time": 8149,
  "schema_version": 8,
  "seed": "2ESMGK6ZLW",
  "start_time": 1773795134,
  "was_abandoned": false,
  "win": true
}