{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 6,
  "build_id": "v0.100.0",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.QUEEN_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "NEW_LEAF",
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "HEFTY_TABLET",
                "title": {
                  "key": "HEFTY_TABLET.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.NO_ESCAPE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_NECROBINDER"
                }
              }
            ],
            "current_gold": 99,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NEW_LEAF.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.NEW_LEAF",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BORROWED_TIME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BORROWED_TIME"
              }
            ],
            "current_gold": 110,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.NIBBITS_WEAK",
            "monster_ids": [
              "MONSTER.NIBBIT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.SOWN"
                  },
                  "floor_added_to_deck": 2,
                  "id": "CARD.BORROWED_TIME"
                },
                "enchantment": "ENCHANTMENT.SOWN"
              }
            ],
            "current_gold": 110,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SAPPHIRE_SEED.pages.INITIAL.options.PLANT.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Sown"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SAPPHIRE_SEED",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEGATIVE_PULSE"
              }
            ],
            "current_gold": 121,
            "current_hp": 45,
            "damage_taken": 7,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEATH_MARCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 132,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 132,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NEGATIVE_PULSE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.REAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MELANCHOLY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.REAP"
              }
            ],
            "current_gold": 139,
            "current_hp": 37,
            "damage_taken": 8,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CUBEX_CONSTRUCT_NORMAL",
            "monster_ids": [
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.DEATHS_DOOR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEATHS_DOOR"
              }
            ],
            "current_gold": 148,
            "current_hp": 29,
            "damage_taken": 8,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VINE_SHAMBLER_NORMAL",
            "monster_ids": [
              "MONSTER.VINE_SHAMBLER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.NEUROSURGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEUROSURGE"
              }
            ],
            "current_gold": 157,
            "current_hp": 17,
            "damage_taken": 12,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_DOOM",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.DEXTERITY_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FLYCONID_NORMAL",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.FLYCONID"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 191,
            "current_hp": 17,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.UNSETTLING_LAMP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 191,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CLUMSY"
              }
            ],
            "current_gold": 191,
            "current_hp": 36,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.ORNATE.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 191,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.HAUNT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DREDGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HAUNT"
              }
            ],
            "current_gold": 204,
            "current_hp": 54,
            "damage_taken": 1,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.GIGANTIFICATION_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INKLETS_NORMAL",
            "monster_ids": [
              "MONSTER.INKLET",
              "MONSTER.INKLET",
              "MONSTER.INKLET"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SQUEEZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              }
            ],
            "current_gold": 230,
            "current_hp": 39,
            "damage_taken": 15,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_OF_DOOM"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LUCKY_FYSH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 230,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NO_ESCAPE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.END_OF_DAYS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SQUEEZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MISERY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.END_OF_DAYS"
              }
            ],
            "current_gold": 320,
            "current_hp": 33,
            "damage_taken": 6,
            "gold_gained": 90,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.RADIANT_TINCTURE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.VANTOM_BOSS",
            "monster_ids": [
              "MONSTER.VANTOM"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_FLESH",
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_WING",
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_BLOOD",
                "title": {
                  "key": "PAELS_BLOOD.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 320,
            "current_hp": 59,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_BLOOD.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 26,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_BLOOD",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.CLEANSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RIGHT_HAND_HAND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CLEANSE"
              }
            ],
            "current_gold": 342,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 22,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 20,
                  "id": "CARD.DELAY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.NO_ESCAPE"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.DELAY"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 1,
                "id": "CARD.NO_ESCAPE"
              }
            ],
            "current_gold": 382,
            "current_hp": 53,
            "damage_taken": 6,
            "gold_gained": 40,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.INVOKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SIC_EM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.INVOKE"
              }
            ],
            "current_gold": 407,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 25,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.FAKE_HAPPY_FLOWER",
              "RELIC.FAKE_VENERABLE_TEA_SET"
            ],
            "current_gold": 301,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 106,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FAKE_HAPPY_FLOWER",
                "was_picked": true
              },
              {
                "choice": "RELIC.FAKE_VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.FAKE_MERCHANT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.PAGESTORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WISP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PAGESTORM"
              }
            ],
            "current_gold": 323,
            "current_hp": 43,
            "damage_taken": 10,
            "gold_gained": 22,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CHOMPERS_NORMAL",
            "monster_ids": [
              "MONSTER.CHOMPER",
              "MONSTER.CHOMPER"
            ],
            "room_type": "monster",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HIGH_FIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BONE_SHARDS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CATASTROPHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANOINTED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DIRGE"
              },
              {
                "id": "CARD.SHROUD"
              },
              {
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 119,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 249,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.GORGET",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 25,
                  "id": "CARD.TIMES_UP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PUTREFY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TIMES_UP"
              }
            ],
            "current_gold": 170,
            "current_hp": 15,
            "damage_taken": 28,
            "gold_gained": 51,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.DUPLICATOR"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 215,
            "current_hp": 15,
            "damage_taken": 0,
            "gold_gained": 45,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 215,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PULL_FROM_BELOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.WISP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 228,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 228,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 246,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.CLAIM.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Lost Wisp"
                  },
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Decay"
                  }
                }
              }
            ],
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LOST_WISP",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.LOST_WISP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.SEVERANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNDEATH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SEVERANCE"
              }
            ],
            "current_gold": 305,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 59,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BOOKMARK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.ENTOMANCER_ELITE",
            "monster_ids": [
              "MONSTER.ENTOMANCER"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 305,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.TIMES_UP"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.NEUROSURGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ERADICATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SACRIFICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEUROSURGE"
              }
            ],
            "current_gold": 416,
            "current_hp": 40,
            "damage_taken": 13,
            "gold_gained": 111,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "DIAMOND_DIADEM",
                "title": {
                  "key": "DIAMOND_DIADEM.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "BRILLIANT_SCARF",
                "title": {
                  "key": "BRILLIANT_SCARF.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "FUR_COAT",
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 416,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BRILLIANT_SCARF.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BRILLIANT_SCARF",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 35,
                  "id": "CARD.NEGATIVE_PULSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NEGATIVE_PULSE"
              }
            ],
            "current_gold": 447,
            "current_hp": 49,
            "damage_taken": 11,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 447,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "RANWID_THE_ELDER.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Potion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Vulnerable Potion"
                  },
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Venerable Tea Set"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_discarded": [
              "POTION.VULNERABLE_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORNAMENTAL_FAN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.RANWID_THE_ELDER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WISP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 462,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 462,
            "current_hp": 49,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "POTION_COURIER.pages.INITIAL.options.GRAB_POTIONS.title",
                  "table": "events"
                },
                "variables": {
                  "FoulPotions": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.FOUL_POTION",
                "was_picked": false
              }
            ],
            "potion_discarded": [
              "POTION.TOUCH_OF_INSANITY",
              "POTION.SPEED_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.POTION_COURIER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.BLOOD_VIAL",
              "RELIC.BAG_OF_MARBLES"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BURY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DANSE_MACABRE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.JACK_OF_ALL_TRADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ETERNAL_ARMOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHARED_FATE"
              },
              {
                "id": "CARD.CAPTURE_SPIRIT"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 30,
                "id": "CARD.DECAY"
              }
            ],
            "current_gold": 14,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 286,
            "gold_lost": 0,
            "gold_spent": 734,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": false
              },
              {
                "choice": "POTION.POTION_OF_DOOM",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              }
            ],
            "potion_used": [
              "POTION.FOUL_POTION",
              "POTION.FOUL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": true
              },
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              },
              {
                "choice": "RELIC.SCREAMING_FLAGON",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 14,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DIRGE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 54,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 40,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PANTOGRAPH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 54,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                },
                "variables": {
                  "Setting1Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 75,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting2Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 150,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting3Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 300,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "upgraded_cards": [
              "CARD.DEFEND_NECROBINDER",
              "CARD.NEUROSURGE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BATTLEWORN_DUMMY",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.BATTLEWORN_DUMMY_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.BATTLE_FRIEND_V2"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLIGHT_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 65,
            "current_hp": 48,
            "damage_taken": 5,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GLOBE_HEAD_NORMAL",
            "monster_ids": [
              "MONSTER.GLOBE_HEAD"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 44,
                  "id": "CARD.DEFY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHROUD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.REAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.DEFY"
              }
            ],
            "current_gold": 93,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
            "monster_ids": [
              "MONSTER.SLIMED_BERSERKER"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 45,
                  "id": "CARD.OBLIVION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LETHALITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.NO_ESCAPE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.OBLIVION"
              }
            ],
            "current_gold": 127,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
            "monster_ids": [
              "MONSTER.THE_LOST",
              "MONSTER.THE_FORGOTTEN"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.WISP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              }
            ],
            "current_gold": 143,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 16,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.VULNERABLE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CONSTRUCT_MENAGERIE_NORMAL",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 143,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.OBLIVION"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 143,
            "current_hp": 0,
            "damage_taken": 60,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 12,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.QUEEN_BOSS",
            "monster_ids": [
              "MONSTER.TORCH_HEAD_AMALGAM",
              "MONSTER.QUEEN"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.SOWN"
          },
          "floor_added_to_deck": 2,
          "id": "CARD.BORROWED_TIME"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.NEGATIVE_PULSE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.REAP"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.DEATHS_DOOR"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.NEUROSURGE"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.CLUMSY"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.HAUNT"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.END_OF_DAYS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.CLEANSE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.NO_ESCAPE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.DELAY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.INVOKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.PAGESTORM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 24,
          "id": "CARD.DIRGE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "CARD.SHROUD"
        },
        {
          "floor_added_to_deck": 24,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 25,
          "id": "CARD.TIMES_UP"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.SEVERANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.NEUROSURGE"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.NEGATIVE_PULSE"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.SHARED_FATE"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.CAPTURE_SPIRIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 44,
          "id": "CARD.DEFY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 45,
          "id": "CARD.OBLIVION"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NEW_LEAF"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.UNSETTLING_LAMP"
        },
        {
          "floor_added_to_deck": 12,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 15,
          "id": "RELIC.LUCKY_FYSH"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.PAELS_BLOOD"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.FAKE_HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 4
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.FAKE_VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 25,
          "id": "RELIC.BOWLER_HAT"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 30,
          "id": "RELIC.LOST_WISP"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.BOOKMARK"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.BRILLIANT_SCARF"
        },
        {
          "floor_added_to_deck": 36,
          "id": "RELIC.ORNAMENTAL_FAN"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.BLOOD_VIAL"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.PANTOGRAPH"
        }
      ]
    }
  ],
  "run_time": 2536,
  "schema_version": 8,
  "seed": "P2ZUQRTVK9",
  "start_time": 1774242660,
  "was_abandoned": false,
  "win": false
}